name: Mirror to Codeberg

on:
  push:
    branches: ["**"]
    tags: ["**"]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Es necesario para obtener todas las ramas y etiquetas

      - name: Mirror a Codeberg
        uses: cssnr/mirror-repository-action@v1
        with:
          host: https://codeberg.org
          username: encicat
          password: ${{ secrets.CODEBERG_TOKEN }}
          repository: encicat/website
          create: true
